<?php
/**
 * @file
 * Contains template_helpers.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function template_helpers_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    case 'help.page.template_helpers':
      $output = '';
      $output .= '<h3>' . t('Ckeditor Template Helpers') . '</h3>';
      $output .= '<p>' . t('The module adds alternative way to define widgets in CKEditor') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Settings') . '</dt>';
      $output .= '<dd>' . t('In the <a href=":text-formats">text formats</a> that use ckeditor, move the Template Helpers icon into the active toolbar.', [':text-formats' => \Drupal::url('filter.admin_overview')]) . '</dd>';
      $output .= '</dl>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function template_helpers_page_attachments_alter(array &$page) {
  // Attaches js assets globally.
  //$page['#attached']['library'][] = 'template_helpers/template_helpers';
  $page['#attached']['drupalSettings']['template_helpers']['widgetDefinitions'] = [];
}
